version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-service
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_secret
    volumes:
      - minio-data:/data
    command:
      minio server --console-address ":9001" /data
volumes:
  minio-data:
    driver: local


    